name: Schedule Run

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  execute-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Code
        uses: actions/checkout@v4

      - name: Setup Python Runtime
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Network Modules
        run: pip install requests

      - name: Execute Handshake Process
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          TARGET_REPO: ${{ secrets.TARGET_REPO }}
          GH_API: ${{ secrets.GH_API }}
          URL_A: ${{ secrets.URL_A }}
          URL_B: ${{ secrets.URL_B }}
          ORIG_URL: ${{ secrets.ORIG_URL }}
          REF_URL: ${{ secrets.REF_URL }}
          HDR_DEV: ${{ secrets.HDR_DEV }}
          HDR_VIA_KEY: ${{ secrets.HDR_VIA_KEY }}
          EXT_LIST: ${{ secrets.EXT_LIST }}
          TOK_KEYS: ${{ secrets.TOK_KEYS }}
          KEY_A: ${{ secrets.KEY_A }}
          KEY_B: ${{ secrets.KEY_B }}
          KEY_C: ${{ secrets.KEY_C }}
          KEY_D: ${{ secrets.KEY_D }}
          KEY_E: ${{ secrets.KEY_E }}
          KEY_F: ${{ secrets.KEY_F }}
          KEY_G: ${{ secrets.KEY_G }}
          KEY_H: ${{ secrets.KEY_H }}
          KEY_I: ${{ secrets.KEY_I }}
          P_URL_1: ${{ secrets.P_URL_1 }}
          P_URL_2: ${{ secrets.P_URL_2 }}
          P_URL_3: ${{ secrets.P_URL_3 }}
          Z_DISCORD_WEBHOOK: ${{ secrets.Z_DISCORD_WEBHOOK }}
        run: python main.py
